# Generated by Django 3.2.9 on 2022-03-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb_list_app', '0006_review_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='total_rating',
            field=models.IntegerField(default=0),
        ),
    ]
