# Generated by Django 3.2.9 on 2022-03-14 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb_list_app', '0008_auto_20220310_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='img',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to='pictures/%Y/%m/%d'),
        ),
    ]
