# Generated by Django 3.2.9 on 2022-03-14 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imdb_list_app', '0009_watchlist_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='img',
        ),
    ]
