# Generated by Django 3.2.9 on 2022-03-15 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb_list_app', '0011_watchlist_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='trailor',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
